# Generated by Django 4.0.3 on 2022-05-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic_saver', '0004_rename_file_image_image_image_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
